version: 0.1

phases:
   pre_build: 
     commands:
     
   build:
     commands:
     
artifacts:
  files:
   - public/*

 ## CODEBUILD_SOURCE_VERSION
 ## CODEBUILD_WEBHOOK_BASE_REF    
  name: profileapp-$(CODEBUILD_WEBHOOK_BASE_REF) 