version: 0.2


env:
  variables:
    BUILD_BRANCH: myArtifactName

phases:
   pre_build: 
     commands:
      
      - echo $CODEBUILD_WEBHOOK_HEAD_REF

      - echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -f3 -d"/"
      
      - export BRANCH_BUILD=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -f3 -d"/")
     
     
   build:
     commands:
     
artifacts:
  files:
   - public/*
  
  #$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -f3 -d"/") 
 
  name: profileapp-$Env:BRANCH_BUILD

 ## CODEBUILD_SOURCE_VERSION
 ## CODEBUILD_WEBHOOK_BASE_REF    
 