version: 0.1


env:
  variables:
    BUILD_BRANCH: myArtifactName

phases:
   pre_build: 
     commands:
      
      - echo $CODEBUILD_WEBHOOK_HEAD_REF

      - echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -f1-2 -d"/"
     
     
   build:
     commands:
     
artifacts:
  files:
   - public/*

  name: profileapp-$(CODEBUILD_WEBHOOK_HEAD_REF | cut -f1 -d"/") 
 

 ## CODEBUILD_SOURCE_VERSION
 ## CODEBUILD_WEBHOOK_BASE_REF    
 